autoInstallPeers: false

blockExoticSubdeps: true

overrides:
  prettier-plugin-expand-json: '-'
  vite-plus>oxfmt: '-'

peerDependencyRules:
  allowAny:
    - vitest

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade
